language: java

before_script:
  - mysql -u root < project-resources/init-mysql.sql
  - psql -U postgres -f project-resources/init-psql.sql

script:
  - "mvn test -P integration"
  - "mvn deploy --settings project-resources/ci-settings.xml"

branches:
  only:
    - master

env:
  global:
    - secure: "DcgB1wHDG1GiFZukDbUnHctE9iA1GogSyIqtsVnPdtVa9OelkVMtb7uVeb1S/X02rjGhrI8f1VGZ6Vqnm8+Uvqf91lMPrpn5/EBQ9LOUJEIqDErXswAWQTSa4yxwAhUGE99eI9pglxh40dAGmDhrKe7Lq1lnQbr3IGUrYgnolLw=" 
