language: java
script: "mvn deploy --settings project-resources/ci-settings.xml"

branches:
  only:
    - master

env:
  global:
    - secure: "fVwI32/S/+4AzyWxriYf7KLSc6PItRYMXKAI+e3yGF0V+ZAUHZUocrBFkerOE8T7qOkHdr4Sr+7xeahWMKQOg4ySmpeUn0+TT5YNZDtfcGy53DuJHaPFO9eJ6R8gx6Pn1idDtq06FDVXHGH9jsokm/QIQd1ddcXK7M2RYmaZ9RI="
